[prune]
  go-tests = true

[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "https://github.com/fsnotify/fsnotify.git"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.3.0"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "1.2.0"

[[constraint]]
  name = "github.com/tyler-smith/go-bip39"
  revision = "dbb3b84ba2ef14e894f5e33d6c6e43641e665738"

[[constraint]]
  name = "github.com/asticode/go-astilectron"
  branch = "master"

[[override]]
  name = "github.com/asticode/go-astilectron-bundler"
  branch = "master"